name: Compile PDF
on: [push]
jobs:
  building:
    runs-on: ubuntu-latest
    container:
      image: texlive/texlive
      # Need root, otherwise this exact issue occurs:
      # https://github.community/t/permission-problems-when-checking-out-code-as-part-of-github-action/202263
      options: --user root
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build all LaTeX PDFs
        run: latexmk
        working-directory: ./report
      - name: Archive compilation artifacts
        uses: actions/upload-artifact@v3
        with:
          name: pdfs
          path: ./*.out/*.pdf
          if-no-files-found: error
        working-directory: ./report