[server]
## IP address: Red Pitaya address or 
## 'localhost' if emulating a local server with marcos_server through verilator (marga)
ip_address = "192.168.1.100" # e.g. 192.168.1.189

## Port where marcos_server is running
port = 11111

## FPGA clock frequency (Right now only 122.88 is supported)
fpga_clk_freq_MHz = 122.88 # RP-122, alternative: 125.0  # RP-125

## Gradient board data format (either "gpa-fhdo" or "ocra1")
grad_board = "gpa-fhdo" # "ocra1"

## GPA-FHDO current per volt setting (determined by resistors)
gpa_fhdo_current_per_volt = 2.5

[client]
## Flocra-pulseq path, for use of the flocra-pulseq library (optional).
## Uncomment the lines below and adjust the path to suit your
## flocra-pulseq location.
flocra_pulseq = "/home/mstabel/Projects/nmr-spectrometer/workspace/marcos/marcos_pack/ocra-pulseq"

[simulator]
# relative paths are relative to the current working directory when executing the commands!
path = "../marga"  
csv = "/tmp/marga_sim.csv"

# Set to True to debug with GTKWave -- just do one test at a time!
fst_dump = false
fst = "/tmp/marga_sim.fst"

mem_file = "/tmp/marcos_server_mem"