**************************************
*      Model Generated by MODPEX     *
*Copyright(c) Symmetry Design Systems*
*         All Rights Reserved        *
*    UNPUBLISHED LICENSED SOFTWARE   *
*   Contains Proprietary Information *
*      Which is The Property of      *
*     SYMMETRY OR ITS LICENSORS      *
*Commercial Use or Resale Restricted *
*   by Symmetry License Agreement    *
**************************************
* Model generated on Jan 17, 05
* MODEL FORMAT: SPICE3
.MODEL mmsd301t1 d
+IS=7.59492e-08 RS=4.93246 N=1.53455 EG=0.608881
+XTI=4 BV=30 IBV=1e-05 CJO=2.26925e-12
+VJ=0.4 M=0.260918 FC=0.5 TT=2.98638e-09
+KF=0 AF=1


