**************************************
*      Model Generated by MODPEX     *
*Copyright(c) Symmetry Design Systems*
*         All Rights Reserved        *
*    UNPUBLISHED LICENSED SOFTWARE   *
*   Contains Proprietary Information *
*      Which is The Property of      *
*     SYMMETRY OR ITS LICENSORS      *
*Commercial Use or Resale Restricted *
*   by Symmetry License Agreement    *
**************************************
* Model generated on Nov 11, 03
* MODEL FORMAT: SPICE3
.MODEL ss12t3 d
+IS=2.28268e-05 RS=0.0336389 N=1.42941 EG=0.707069
+XTI=0.005 BV=20 IBV=4.5e-05 CJO=4.4488e-10
+VJ=0.04 M=0.394446 FC=0.5 TT=0
+KF=0 AF=1


