name: Compile Report PDF
on: [push]
jobs:
  compile:
    runs-on: ubuntu-latest
    container:
      image: texlive/texlive
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build all LaTeX PDFs
        run: latexmk
        working-directory: ./report
      - name: Archive compilation artifacts
        uses: actions/upload-artifact@v3
        with:
          name: pdfs
          path: ./*.out/*.pdf
          if-no-files-found: error
        working-directory: ./report